name: E2E Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - name: Cache node modules
      run: npm ci
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    - name: Run E2E tests
      run: npm run test:e2e
    - name: Upload Cucumber report
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-report
        path: cucumber-report.html